name: Lint, build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DISCORD_TOKEN: 'FAKE_TOKEN'
  AIRTABLE_TOKEN: 'FAKE_AIRTABLE_TOKEN'
  AIRTABLE_BASE: 'FAKE_TABLE_NAME'
  GUILD_ID: 'FAKE_DEV_DAO_ID'
  CLIENT_ID: 'FAKE_CLIENT_ID'

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install modules
      run: npm install
    - name: Run lint script
      run: npm run lint
    - name: Run test
      run: npm run test
